(in-package :mgl)

(defsection @mgl-readme (:title "MGL")
  (mgl asdf:system)
  (@mgl-overview section)
  (@mgl-links section)
  (@mgl-documentation section))

(defsection @mgl-documentation (:title "Documentation")
  "Documentation for this version is available in markdown format in
  [MGL Manual](doc/md/mgl-manual.md). [HTML
  documentation](http://melisgl.github.io/mgl-pax-world/mgl-manual.html)
  is generated for the latest version.")

;;;; Generating docs for MGL. Not included in the ASDF system.

(defun update-readmes ()
  ;; README.md has anchors, links, inline code, and other markup
  ;; added. Not necessarily the easiest on the eye in text, but looks
  ;; good on github.
  (with-open-file (stream (asdf:system-relative-pathname :mgl "README.md")
                          :direction :output
                          :if-does-not-exist :create
                          :if-exists :supersede)
    (document @mgl-readme :stream stream)
    (print-markdown-footer stream))
  ;; README is optimized for reading in text format. Has no links and
  ;; cluttery markup.
  (with-open-file (stream (asdf:system-relative-pathname :mgl "README")
                          :direction :output
                          :if-does-not-exist :create
                          :if-exists :supersede)
    (describe @mgl-readme stream)
    (print-markdown-footer stream)))

(defun update-md ()
  (with-open-file (stream (ensure-directories-exist
                           (asdf:system-relative-pathname
                            :mgl "doc/md/mgl-manual.md"))
                          :direction :output
                          :if-does-not-exist :create
                          :if-exists :supersede)
    (document @mgl-manual :stream stream)
    (print-markdown-footer stream)))

(defun print-markdown-footer (stream)
  (format stream "~%* * *~%")
  (format stream "###### \\[generated by ~
                   [MGL-PAX](https://github.com/melisgl/mgl-pax)\\]~%"))

#|

(progn
 (update-readmes)
 (update-md))

|#
