
(defun diff-mats (x y)
  (with-facets ((x* (x 'array :direction :input))
                (y* (y 'array :direction :input)))
    (assert (= (length x*) (length y*)))
    (dotimes (i (length x*))
      (let ((xi (aref x* i))
            (yi (aref y* i)))
        (when (< 0.0001d0 (abs (- xi yi)))
          (error "~S: ~S ~S~%" i xi yi))))))
